#
# Copyright (c) 2022-2023 helloworld <https://github.com/fw876/helloworld>
# Description: Build SSR-Plus+
#

name: Sync
run-name: Sync SSR-Plus+

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_TOKEN: ${{ secrets.ACCESS_TOKEN }} 

on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'packages'
        required: false
        default: 'false'

permissions: write-all        

jobs:
  sync_ssrp:
    runs-on: ubuntu-latest
    name: Sync ${{matrix.branch}}
    strategy:
      fail-fast: false
      matrix:
        branch: [master]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
      with:
        fetch-depth: 0

    - name: Init environment
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"
        
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x .github/diy/${{matrix.branch}}.sh
        git clone -b ${{matrix.branch}} https://github.com/love-dy/openwrt-ssrplus.git ${{matrix.branch}}
        
        cd ${{matrix.branch}}
        git rm -r --cache * >/dev/null 2>&1 &
        rm -rf `find ./* -maxdepth 0 -type d ! -name "diy"` >/dev/null 2>&1
        $GITHUB_WORKSPACE/.github/diy/${{matrix.branch}}.sh
        bash /$GITHUB_WORKSPACE/.github/diy/convert_translation.sh
        bash /$GITHUB_WORKSPACE/.github/diy/create_acl_for_luci.sh -a
        bash /$GITHUB_WORKSPACE/.github/diy/Modify.sh

    - name: Upload packages
      run: |
        if [ -e $GITHUB_WORKSPACE/LICENSE ]; then
          cp $GITHUB_WORKSPACE/LICENSE $GITHUB_WORKSPACE/${{matrix.branch}}
        fi
        if [ -e $GITHUB_WORKSPACE/README.md ]; then
          cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/${{matrix.branch}}
        fi
        cd $GITHUB_WORKSPACE/${{matrix.branch}}
        if git status --porcelain | grep .; then
          git add .
          git commit -am "update $(date '+%Y-%m-%d %H:%M:%S')"
          git push --quiet "https://${{ secrets.ACCESS_TOKEN }}@github.com/love-dy/openwrt-ssrplus.git" HEAD:${{matrix.branch}}
        else
          echo "nothing to commit"
          exit 0
        fi || exit 0

    - name: Delete Old Workflows    
      uses: Mattraks/delete-workflow-runs@v2.0.4
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        #计算到目前为止每个工作流已保留的天数, 达到指定的天数工作流将被删除
        retain_days: 1
        #为每个工作流保留的最少运行次数
        keep_minimum_runs: 0  



        
#  #########################################################



 
